// import { Icon } from '@iconify/react';

import { SideNavItem } from "./types";

export const SIDENAV_ITEMS: SideNavItem[] = [
  {
    title: "General Section",
    path: "/general/crcp",
    submenu: true,
    subMenuItems: [
      { title: "CRCP", path: "/general/crcp" },
      { title: "JRCP", path: "/general/jrcp" },
      { title: "CPCD", path: "/general/cpcd" },
    ],
  },
  {
    title: "Special Section",
    path: "/special/whitetopping",
    submenu: true,
    subMenuItems: [
      { title: "Whitetopping", path: "/special/whitetopping" },
      { title: "FT", path: "/special/ft" },
      { title: "PRCP", path: "/special/prcp" },
      { title: "PCP", path: "/special/pcp" },
    ],
  },
  {
    title: "Statistics",
    path: "/statistics/pmis",
    submenu: true,
    subMenuItems: [{ title: "PMIS", path: "/statistics/pmis" }],
  },
  {
    title: "Project Evaluation",
    // title: 'Project Level Evaluation',
    path: "/project_eva/whitetopping",
    submenu: true,
    subMenuItems: [
      { title: "Whitetopping", path: "/project_eva/whitetopping" },
      { title: "FT", path: "/project_eva/ft" },
      { title: "PRCP", path: "/project_eva/prcp" },
      { title: "PCP", path: "/project_eva/pcp" },
    ],
  },
  {
    title: "Documentation",
    path: "/documentation/forensic",
    submenu: true,
    subMenuItems: [
      { title: "Forensic", path: "/documentation/forensic" },
      { title: "Research", path: "/documentation/research" },
    ],
  },
];

export const LEVEL_1_SECTION_ROWS = [
  {
    index: 0,
    sectionId: "2-I35-1",
    highway: "IH 35W",
    district: "Ft. Worth",
    county: "Tarrant",
    direction: "S",
    pavementType: "CRCP",
  },
  {
    index: 1,
    sectionId: "2-I820-1",
    highway: "IH 820",
    district: "Ft. Worth",
    county: "Tarrant",
    direction: "NE",
    pavementType: "CRCP",
  },
  {
    index: 2,
    sectionId: "3-I35-1",
    highway: "IH 35",
    district: "Wichita Falls",
    county: "Cooke",
    direction: "N",
    pavementType: "CRCP",
  },
  {
    index: 3,
    sectionId: "3-US287-1",
    highway: "US 287",
    district: "Wichita Falls",
    county: "Wichita",
    direction: "N",
    pavementType: "CRCP",
  },
  {
    index: 4,
    sectionId: "3-US287-2",
    highway: "US 287",
    district: "Wichita Falls",
    county: "Wichita",
    direction: "N",
    pavementType: "CRCP",
  },
  {
    index: 5,
    sectionId: "4-I40-1",
    highway: "IH 40",
    district: "Amarillo",
    county: "Oldham",
    direction: "W",
    pavementType: "CRCP",
  },
  {
    index: 6,
    sectionId: "5-I27-1",
    highway: "IH 27",
    district: "Lubbock",
    county: "Hale",
    direction: "S",
    pavementType: "CRCP",
  },
  {
    index: 7,
    sectionId: "5-Loop_289-1",
    highway: "Loop 289",
    district: "Lubbock",
    county: "Lubbock",
    direction: "N",
    pavementType: "CRCP",
  },
  {
    index: 8,
    sectionId: "9-I35-1",
    highway: "IH 35",
    district: "Waco",
    county: "Hill",
    direction: "S",
    pavementType: "CRCP",
  },
  {
    index: 9,
    sectionId: "9-I35-2",
    highway: "IH 35",
    district: "Waco",
    county: "McLennan",
    direction: "N",
    pavementType: "CRCP",
  },
  {
    index: 10,
    sectionId: "12-441-1-2",
    highway: "IH 45",
    district: "Houston",
    county: "Montgomery",
    direction: "N",
    pavementType: "CRCP",
  },
  {
    index: 11,
    sectionId: "12-US290-1",
    highway: "US 290",
    district: "Houston",
    county: "Waller",
    direction: "E",
    pavementType: "preformed/ sawcut CRCP",
  },
  {
    index: 12,
    sectionId: "12-US290-2",
    highway: "US 290",
    district: "Houston",
    county: "Waller",
    direction: "W",
    pavementType: "CRCP",
  },
  {
    index: 13,
    sectionId: "12-US290-3",
    highway: "US 290",
    district: "Houston",
    county: "Waller",
    direction: "E",
    pavementType: "CRCP",
  },
  {
    index: 14,
    sectionId: "18-I30-1",
    highway: "IH 30",
    district: "Dallas",
    county: "Dallas",
    direction: "W",
    pavementType: "CRCP",
  },
  {
    index: 15,
    sectionId: "19-US59-1",
    highway: "US 59",
    district: "Atlanta",
    county: "Bowie",
    direction: "S",
    pavementType: "CRCP",
  },
  {
    index: 16,
    sectionId: "19-US59-2",
    highway: "US 59",
    district: "Atlanta",
    county: "Cass",
    direction: "S",
    pavementType: "CRCP",
  },
  {
    index: 17,
    sectionId: "20-I10-1",
    highway: "IH 10",
    district: "Beaumont",
    county: "Orange",
    direction: "E",
    pavementType: "CRCP",
  },
  {
    index: 18,
    sectionId: "24-I10-1",
    highway: "IH 10",
    district: "El Paso",
    county: "El Paso",
    direction: "E",
    pavementType: "CRCP",
  },
  {
    index: 19,
    sectionId: "24-I10-2",
    highway: "IH 10",
    district: "El Paso",
    county: "El Paso",
    direction: "E",
    pavementType: "CRCP",
  },
  {
    index: 20,
    sectionId: "24-I10-3",
    highway: "IH 10",
    district: "El Paso",
    county: "El Paso",
    direction: "W",
    pavementType: "CRCP",
  },
  {
    index: 21,
    sectionId: "24-I10-4",
    highway: "IH 10",
    district: "El Paso",
    county: "Hudspeth",
    direction: "W",
    pavementType: "CRCP",
  },
  {
    index: 22,
    sectionId: "25-I40-1",
    highway: "IH 40",
    district: "Childress",
    county: "Wheeler",
    direction: "W",
    pavementType: "CRCP",
  },
  {
    index: 23,
    sectionId: "25-I40-2",
    highway: "IH 40",
    district: "Childress",
    county: "Wheeler",
    direction: "N",
    pavementType: "CRCP",
  },
];